### ISSUE TITLE
server platform specific code

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/brisky-app-server#9]
device <-- use device
- tv
- phone
- default <--- this is the default

use vigour-ua to determine device (from ua) then server the correct assets

**Comment by jimdebeer** [comment]
serve from the cwd()

**Comment by jimdebeer** [comment]
and for this you can use vigour-ua

**Comment by mstdokumaci** [comment]
serves from any given path, cwd can be given on server creation.
